socrata/shipyard

- base/Dockerfile
- base/ship
This change introduces a directory /etc/pre-init.d/, which is processed using run-parts. Scripts in this directory are executed before the main app runs. The intent is to provide a mechanism for images derived from base to hook in to the container initialization process in order to perform any required run-time initialization.
Any example use case for this mechanism is the key management system, which will provide scripts to retrieve and decrypt application specific credentials, etc.
> Run the contents of /etc/pre-init.d before executing the main command

- base/Dockerfile
- java/Dockerfile
- create socrata user so apps can run as non-root for security reasons.  It isn't ideal that
it is a shared uid, but the real solution to that is uid namespaces.  Even if each image
created its own user, that wouldn't avoid uid sharing so may as well do it here.
- keep apt-get update and install in one RUN command to avoid potential caching pitfalls, and minimize
the number of unnecessary RUN layers.
- Use COPY instead of ADD when you don't need ADD's features, and reduce the number of layers.
- don't leave unnecessary stuff in /var/cache/oracle-jdk7-installer to reduce image size.
> A few cleanups, following guidance from https://docs.docker.com/articles/dockerfile_best-practices/

- base/Dockerfile
- java/Dockerfile
This seems to be a common practice among Dockerfiles to slim them down the resulting image a
bit.
([for example](https://github.com/docker-library/rails/blob/master/Dockerfile))
> Clean up apt list cache after apt-get updates

- base/ship
The default ulimit of 1024 is stone age and not enough for most server applications.  Let's raise it for everyone.
> Raise the ulimit for everyone

- python/Dockerfile
- python/README.md
Alrighty ops team.   Between what I read from the comments on Nick's PR,  what other base python images pull in and what I envision as a base python image, this is what I'm suggesting for our base python image.
I'm uncertain of one thing though:  should I use the 'python' namespace, or should this be named 'python2' or 'python2.7'?
This builds and runs fine locally.
> Base python image

- base/Dockerfile
- base/env_parse
to env_parse and have them be lists in the template.
Also, moves up the `gem install` since COPY and STEPS invalidate caching of following steps
> Add ability to pass in _LIST postfixed environment variables

- base/set_metrics_dir
Files found under the metrics container directory will now inherit from Metrics directory.
- Restricted write and execution permission to container owner and group.
> Group Permission inheritence

- base/set_metrics_dir
This reverts commit 6404aa75c96bf21da6aa42ee9f63a836867dbd8e.
Was breaking odysseus build.
> Revert "Make creation of metrics dir happen as the socrata user."

- frontend-12_04/Dockerfile
This fixes a directory tree issue in the `tar` extraction and forces the creation of the symlink to the `phantomjs` executable.
FYI: @JoeNunnelley, @progman32, @michaelb990
Confirmation:
```sh
/usr/bin/phantomjs --version
1.9.1
```
> EN-2758 Fix bug in phantomjs bin path

- python/Dockerfile
- python3/Dockerfile
Some Python modules failed to install due to the fact that locale wasn't
being set. This changeset addresses that.
> Generate and set locales

- README.md
- py3_analysis/Dockerfile
- py3_analysis/README.md
- py3_spacy/Dockerfile
- py3_spacy/README.md
This creates python3 images analogous to some of our python2 images, as well as updates the readme to point to all the images that have cropped up since the last time this was updated.
> Add 2 new python3 images; update the readme

- py3_analysis/Dockerfile
- py3_spacy/Dockerfile
Since Clads is the only consumer of these images and local dev uses the latest versions of these dependencies, I bumped the Dockerfiles to match.
> Bump spacy and scikit-learn versions

- base/clortho-get
This helps to make clortho-get work transparently in SEA1 where we cannot rely on falling back to IAM roles.
> add a check for local aws credentials

- python3/Dockerfile
The latest stable release of Python (3.5.2) isn't available via
apt. With this change, we install it directly from source.
> Build Python3 from source so we can use Python 3.5

- README.md
- ruby/2.3-admin/Dockerfile
Per discussion with Justin, I am moving these package installs out of the base image and into a team-specific docker image that we can share for our projects alone.
Also, experimentally purging some packages which I believe to be unnecessary.
> IMPROVEMENT: Create team-specific image with team specific dependencies

- base/Dockerfile
- ruby/2.3-admin/Dockerfile
* Remove experimental purges
* Update to use upstream image with current tag structure
* Remove package installs from base that I thought I did yesterday.
> FIX: Team-specific image has broken clortho

- runit-java8/set_jmx_hostname
* after marathon upgrade, marathon app ids no longer include environment prefixes
* changes which field to grab for setting APP_NAME
> Account for new marathon app ids when setting APP_NAME

- base/Dockerfile
This seems like the right thing to do to ensure reasonable defaults WRT character sets / encoding in our marathon apps.
> Set en_US.UTF-8 as default locale

- jenkins-worker/Dockerfile
we are getting a bunch of 'unable to set local to UTF-8' in the docker image when frontend builds are run. explicitly setting this in the hopes that those log messages  (of which there are a lot) will be silenced.  I built the image locally and confirmed the correct locale was present in the image.
> explictly initializing en_US.UTF-8 locale on the jenkins worker image

- jenkins-worker/Dockerfile
- rails4-deps/Dockerfile
@rantler reverting what I did on Friday.  Will need to rebuild rails4deps and then rebuild jenkins_frontend-builder image
> Revert jq utility from the frontend images.

- jenkins-worker/Dockerfile
- jenkins-worker/README.md
initializing the base docker image to be configured with locale en_US.UTF-8 which is what the project is asking for but not getting. Right now this produces a bunch of warnings in the frontend builds that are very distracting.  Also updated the README with correct ECR locations.
> utf 8 locale initialization for the base docker image used by frontend, etc.

- rails4-deps/Dockerfile
converting to use the base image that is locked to 2.3.5 for ruby rather than an image whose ruby version floats.
> locking the rails4-deps to use the ruby:2.3.5 base image

- base/Dockerfile
- runit/Dockerfile
In order to meet fedramp requirements, we need to ensure our images are as up-to-date as possible with the provided packages.  
Added one line for `apt-get dist-upgrade -y`.  This should not have an affect on the kernels since the containers utilize the host kernel.
> upgrade
>    upgrade is used to install the newest versions of all packages
>    currently installed on the system from the sources enumerated in
>    /etc/apt/sources.list. Packages currently installed with new
>    versions available are retrieved and upgraded; under no
>    circumstances are currently installed packages removed, or packages
>    not already installed retrieved and installed. New versions of
>    currently installed packages that cannot be upgraded without
>    changing the install status of another …
> On build, do a dist-upgrade

- base/env_parse
Presumably, we want to set env_vars[var_name] to empty list and not wipe out the entire dictionary
of vars in the case of a list variable.
> Fix a small bug

- base/Dockerfile
Explicitly require safe_yaml avoid "uninitialized constant Gem::SafeYAML" error due to version nightmares
> Fix uninitialized constant error in base build.

- python-bionic/2.7/Dockerfile
python-bionic/2.7 was pointing to the `socrata/base` image, which is not `Bionic Beaver`.
Oops
> Reference correct base image

- runit-bionic-python/2.7/Dockerfile
- runit-bionic-python/3.6/Dockerfile
Another testing fail.  Updating the `FROM` to point to `socrata/runit-bionic` instead of `socrata-test`, used locally.  lame.
> Update source of base image

- jenkins-worker/README.md
- jenkins-worker/Worker_Dockerfile
enabling jenkins-worker frontend base image creation for jenkins ec2 worker context. Since the workers have different user UID/GUID  and an 'ubuntu' user that we communicate through, it is necessary to fork the base image worker types.  We will now have a Dockerfile (for the server context) and a Worker_Dockerfile (for the ec2 worker context).  Once we have all frontend, storyteller and common builds on ec2 workers we can remove the legacy builder type (most likely by merging Worker_Dockerfile into Dockerfile
> adding worker context base image with ubuntu and jenkins user setup

- base-bionic/clortho-get
- runit-bionic/clortho-get
Due to a swift hand of incompetence, I updated the shabang to point to
the environments ruby binary, which is incorrect for this specific file.
Returning it back to `#!/usr/bin/ruby` is the ideal solution here.
> Reset ruby shabang in clortho-get

- py3_analysis/Dockerfile
This appears to be an issue with the `pip` command when installing packages where one of the packages in the list depends on another package in the list. Installing the dependencies as separate pip commands avoids the error that was preventing this from building correctly.
Tested by building locally.
> Fix broken docker build

- base-bionic/Dockerfile
- base-xenial/Dockerfile
- base/Dockerfile
- runit-bionic/Dockerfile
- runit/Dockerfile
Prior to this change, when the `aws-sdk-resources` gem is installed when
building base images, we are not disabling the building of gem
documentation. This results in 50-100 megabytes (compressed) of documentation being added to the size of the image.
This change adds the `--no-document` option when `gem install`-ing the
`aws-sdk-resources` gem for our various base images. This saves us
50-100 megabytes (compressed) in our base images.
> NO-JIRA: Do not install gem docs with aws-sdk

- java8-bionic/Dockerfile
- java8-bionic/README.md
- nodejs-bionic/Dockerfile
- nodejs-bionic/README.md
- py3_analysis-bionic/Dockerfile
- py3_analysis-bionic/README.md
- py3_spacy-bionic/Dockerfile
- py3_spacy-bionic/README.md
- python3-bionic/Dockerfile
- python3-bionic/README.md
- ruby-bionic/2.5.3/Dockerfile
- ruby-bionic/README.md
- runit-java8-bionic/Dockerfile
- runit-java8-bionic/README.md
- runit-java8-bionic/collectd-jmx.conf
- runit-java8-bionic/set_jmx_hostname
- runit-nodejs-bionic/10x/Dockerfile
- runit-python-bionic/Dockerfile
- runit-python-bionic/collectd.statsd.conf
- runit-ruby-bionic/2.5.3/Dockerfile
The scope of this change and EN-33791 is to take the trusty-based images that are in-use in marathon and produce bionic versions. Additional versions are out of scope.
Mostly copy trusty Dockerfiles.
The version of python for bionic is 3.6 so that is used for the python3-bionic image rather than installing https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tgz which is done for trusty.
The version of ruby for bionic is 2.5.1 but a 2.5.3 image is created to maintain bug compatibility.
The py3_spacy-bionic image does not attempt to download any model because http://index.spacy.io/ is down.
All images were tested locally with bash as an entrypoint.
> Add bionic versions

- runit-java8-bionic/Dockerfile
Updated path for collectd, typo in LD_LIBRARY_PATH.
> EN-37536: Updated dockerfile for java8-bionic to fix typo

- base-bionic/Dockerfile
While we are here, fix up the package list removal to be part of the
same run command so they don't end up in the worst of both worlds,
taking space in the layer but unusable by anything afterwards.
> Add basic tools to base-bionic.

- runit-bionic/set_collectd_hostname
Quotes were added to the hostname, causing the sed command to fail to match.
Now it matches:
`Hostname "ark-host"`
> Correctly set collectd hostname

- base-bionic/Dockerfile
It is much friendlier for trying to debug stuff in containers than having to
use su.  It got dropped in the trusty -> bionic upgrade.
> Add sudo to bionic-base for debugging.

- runit-bionic/Dockerfile
- runit-bionic/collectd.conf
- runit-bionic/set_collectd_hostname
It seems the newer version of collectd in bionic handles hostnames differently. Simply removing `Hostname` from the config file and letting collectd call `gethostname()` seems to work. Additionally, it was determined that `FQDNLookup false` was needed.
> EN-40079 remove Hostname and rely on gethostname() instead

- .gitattributes
- py3_spacy-bionic/Dockerfile
- py3_spacy-bionic/spacy-data-1.1.0.tgz
Docker hub does not support git-lfs files. This means that previously, when docker hub built this image, it was not
recognizing the spacy data .tgz file as an LFS file and therefore not following the pointer. To work around the absence
of git lfs support, we put the data in a public S3 bucket that we download at docker build time. The tgz file contains
freely available open source code and data.
This has the added benefit that it doesn't put us over our modest Github LFS quota.
Tested locally.
> EN-37882 Download spacy data rather than tracking via git lfs

- runit-ruby-bionic/2.7.2/Dockerfile
- runit-ruby-bionic/3.0.0/Dockerfile
- runit-ruby-bionic/README.md
Updated runit-ruby-bionic Dockerfile for use with ruby 2.7.2 and 3.0.0, removing version pinning for gem and bundler.
Added README for runit-ruby-bionic images.
> EN-44356 - Added runit-ruby-bionic Dockerfiles for 2.7.2 and 3.0.0

- runit-bionic/Dockerfile
- runit-bionic/clortho-get
Copying s3 encryption client changes from base-bionic dockerfile and clortho-get to runit-bionic to make sure they don't diverge per Marc's recommendation.
https://github.com/socrata/shipyard/pull/172#issuecomment-814420921
> Updating S3 encryption client

- base-bionic/Dockerfile
- base-bionic/coredump.conf
- runit-bionic/Dockerfile
- runit-bionic/coredump.conf
Ensuring core dumps don't get turned on in the future if we switch to systemd for init. This also allows us to pass the CIS benchmark we're currently using.
> Adding /etc/systemd/coredump.conf to base images

- py3_spacy-bionic/Dockerfile
- py3_spacy-bionic/README.md
- py3_spacy-bionic/testing/Dockerfile
This image is used by [clads](https://github.com/socrata/clads). Readding it along with a testing tag to see if we can get it building without pinned dependencies.
> Readding py3_spacy-bionic

- runit-elixir/Dockerfile
- runit-elixir/install-elixir
* We want a bugfix that was just released, and erlang-solutions hasn't
even gotten the _previous_ bugfix release out, so we'll just build
erlang from source
* And as a result we need to build elixir too since it depends on
erlang
> Install erlang and elixir from source

- runit-bionic/Dockerfile
Things running inside containers rely on local.dev.socrata.net being remapped in the container
to point back to docker's bridge IP so services running on the host or in other containers
can be reached.
eg.
192.168.65.2    local.dev.socrata.net
Looks like this accidentally got dropped in b6d50ca64231542cd2e57635fb4cf450933e928c.
> Install set_local_dev_hostname in the runit container so local.dev.socrata.net is setup.

- runit-bionic-python/3.8/Dockerfile
- runit-bionic-python/3.8/collectd.statsd.conf
Adds a python 3.8 runit-bionic image, pretty much just something to run osquery-collector on with a version of celery that doesn't have a high severity finding.
> Add python 3.8 runit image for use with updated osquery-collector

- README.md
- ruby-bionic/3.1.x/Dockerfile
- ruby-bionic/3.1.x/hooks/post_push
- ruby-bionic/3.1.x/ruby-version.rb
- ruby-bionic/README.md
- runit-ruby-bionic/3.1.x/Dockerfile
- runit-ruby-bionic/3.1.x/hooks/post_push
- runit-ruby-bionic/3.1.x/ruby-version.rb
- runit-ruby-bionic/README.md
Note these do *not* explicitly set a bundler version as 3.1 comes
with bundler 2.3.3 which is recent enough to not have any known
security vulnerabilities that require a newer verison.
> Add ruby 3.1 bionic images.

- base-focal/Dockerfile
- runit-focal/Dockerfile
Switching from `COPY`ing some files from the local directory to `ADD`ing from an https remote caused them to lose their execute bit.
> Properly set some executables to be executable

- runit-focal/Dockerfile
Because that's where my_init looks for it.  pre-init.d is used by the
"ship" script in the base image.
> Move clortho-get to /etc/my_init.d in runit-focal image

- base-focal/Dockerfile
- runit-focal/Dockerfile
Normal users can't read these scripts we're dumping onto the filesystem currently. This is due to the docker `ADD` command not preserving permissions since we're copying from an HTTPS location. 
Not sure if it will cause a problem, but it's definitely not the way these things were set previously.
> Restore file permissions to what they had previously been

- runit-elixir-focal/Dockerfile
Mainly because the erlang-solutions debs have debug info stripped,
which makes `perf` nearly useless with them.
Also upgrade to erlang 25 because that makes `perf` more useful.
> Build erlang and elixir ourselves

- runit-elixir/Dockerfile
Switch to updated esl-erlang package, download and manually install elixir 1.12
Erlang solutions stopped distributing our previously used versions of the esl-erlang and elixir packages for ubuntu bionic through apt, although they still exist in their package repo.
There are some dependency issues that are tricky to work around with the previous version of esl-erlang we were using, so I bumped it to the latest.
That does satisfy the dependency requirements for elixir 1.12 that we were previously using, so it gets downloaded from the repo and installed via dpkg.
Also switching to the latest erlang-solutions installation package so that it stays up to date in the future.
Removes downloaded debs after installing to reduce clutter and image size.
> Get runit-elixir building again

- ruby-focal/3.2.x/Dockerfile
- ruby-focal/3.2.x/hooks/post_push
- ruby-focal/3.2.x/ruby-version.rb
- ruby-focal/README.md
- runit-ruby-focal/3.2.x/Dockerfile
- runit-ruby-focal/3.2.x/hooks/post_push
- runit-ruby-focal/3.2.x/ruby-version.rb
- runit-ruby-focal/README.md
- Copy/paste from the 3.1.x images, switching to 3.2
- Add `libyaml-dev` to build dependencies
> Create ruby 3.2.x images for focal ruby images

- ruby-focal/3.0.x/Dockerfile
- ruby-focal/3.0.x/hooks/post_push
- ruby-focal/3.0.x/ruby-version.rb
- ruby-focal/README.md
- runit-ruby-focal/3.0.x/Dockerfile
- runit-ruby-focal/3.0.x/hooks/post_push
- runit-ruby-focal/3.0.x/ruby-version.rb
- runit-ruby-focal/README.md
runit-ruby-focal and ruby-focal have only ruby 3.1.x and 3.2.x options.
runit-ruby-focal and ruby-focal also have an option for ruby 3.0.x.
This is what is used for frontend, storyteller and elections currently.
> EN-58985: add focal for ruby 3.0.x

- runit-focal/README.md
- runit-java-focal/README.md
- runit-ruby-focal/README.md
Update runit-focal readme to clarify that runit services need to live in /etc/service, not /etc/sv in the container
Update readmes for runit-java-focal and runit-ruby-focal images to point refer back to the runit-focal readme
> runit-focal readme fix

- ruby-bionic/3.0.x/Dockerfile
- runit-ruby-bionic/3.0.x/Dockerfile
Since ruby 3.0 is now EoL, it no no longer appears when running `ruby-build -l`. This works around that to install the latest minor version of 3.0.
> Fix 3.0 builds

- base-focal-ecs/Dockerfile
- files/clortho-ecs-safe
- files/clortho-get
clortho is causing problems in images running in ECS. This adds a check to the clortho-get in /etc/pre-init.d in all images to see if the container is running inside of ECS and immediately exit if so.
> Check if clortho is running in ECS, stop running clortho if so

- python-focal/3.10/Dockerfile
- python-focal/3.10/README.md
- python-focal/3.11/Dockerfile
- python-focal/3.11/README.md
- runit-python-focal/3.11/Dockerfile
- Add python-focal:3.10 image
- Make python-focal:3.11 behave like other python base images
- Minor corrections to python-focal:3.11 and runit-python-focal:3.11
> python-focal:3.10

- base-bionic/Dockerfile
- runit-bionic/Dockerfile
base-bionic and runit-bionic stopped building due to dropped backwards compatibility in newer versions of some of these gems. 
This also combines the gem install operations into a single docker layer. Using the `--minimal-deps` option to not update already installed dependencies to slim down the final image a little bit more.
The aws-sdk-resources gem kept trying to update aws-sdk-core to a newer version even with it pinned and using `--minimal-deps` added `-f` so that it ignores the fact that it can't update core when installing resources.
> Pin gems to versions that work with ruby 2.5

- java-focal/24/Dockerfile
The openjdk-r ppa doesn't have java 24 yet, using sdkman to install it for now at least.
> Use sdkman to install openjdk 24
