base/Dockerfile
base/clortho-get

Install clortho packages.
Install ruby2.0 in base, for the clortho key management suite
Re-point MAINTAINER to sysadmin@socrata.com

key management support

---

py_analyserver/Dockerfile
py_analyserver/README.md
py_analysis/Dockerfile
py_analysis/README.md
py_nltk/Dockerfile
py_nltk/README.md

on Justin's advice, I have put as much as the animl docker stack as possible into shipyard. The chain of builds looks like:
> socrata/python --> socrata/py_analysis --> socrata/py_nltk --> socrata/py_analyserver --> (clads/pets/animalysis)
I've tested the entire chain locally and everything works great (and is cleaner and faster on our end).
Again though, I have no clue how we want to be name-spacing images, so if y'all would prefer to see different names assigned to these builds, let me know.
p.s. @jhaynes - this commit completely obviates the need for a private-shipyard repo   :)

Animl stack

---

base/Dockerfile
data/Dockerfile
java/Dockerfile
java8/Dockerfile
nodejs/Dockerfile
py_analyserver/Dockerfile
py_analysis/Dockerfile
py_nltk/Dockerfile
python/Dockerfile
rails3-deps/Dockerfile
ruby/1.9/Dockerfile
ruby/2.1/Dockerfile
ruby/2.2/Dockerfile

Beginning of the changes necessary to understand where our docker images are coming from.

Add LABEL command to end of each Dockerfile

---

runit/Dockerfile
runit/README.md
runit/clortho-get
runit/env_parse
runit/set_ark_host
runit/set_ark_hostname
runit/set_metrics_dir
runit/ship
runit/ship.d/run

Copied from base and changed FROM.

New base image copied from base from phusion/baseimage

---

runit-java8/Dockerfile
runit-java8/README.md

Builds and starts on local docker. Doesn't have jmx collectd plugin yet, that's next.

Add runit image with java8 built in

---

python3/Dockerfile
python3/README.md

Added a base Dockerfile for Python3.

Initial check-in of python3 base

---

runit-nodejs/Dockerfile
runit-nodejs/README.md
runit-nodejs/collectd-nodejs.conf

* Added a curl-json collectd plugin
* Upgrade to node 5.1
Refs EN-3114

Add runit-nodejs container

---

runit/sv/collectd-run

Paired-with: noah.meyerhans and robert.voyer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/socrata/shipyard/50)

EN-5117 limit collectd process resident memory

---

rails3-deps/Dockerfile
rails4-deps/Dockerfile

Depends on https://github.com/socrata/frontend/pull/2776

EN-6969 Add nginx to support serving static assets

---

runit-java8-python/Dockerfile
runit-java8-python/README.md

Will speed up build for asset inventory until existing python code has
been removed

Add runit-java8-python image configuration

---

python3/Dockerfile
python3/README.md

Python 3.6 was recently released and is full of awesomeness. This updates our Python3 Dockerfile.

Update Python3 Dockerfile to use Python 3.6

---

jenkins-worker/Dockerfile
jenkins-worker/README.md

also updated documentation to reflect that we don't build this for 12.04 anymore.

Updating worker to latest phantomjs (2.1.1) and latest java (8)

---

jenkins-worker/Dockerfile

@hatmatter @saraid putting the java7 -> java8 conversion back.  we are not supposed to be using java 7 anywhere at this point.

putting java7 -> java8 change back

---

rails4-deps/Dockerfile

@roarkb needs this for his cheetah frontend parser code.

adding jq to the base rails4-deps image

---

jenkins-worker/Dockerfile
rails4-deps/Dockerfile

adding jq back this time for good
this is implementing the work of these two commits that were reverted
https://github.com/socrata/shipyard/commit/7108bcdcb5f84407015c7509b06a592f92b23e8e
https://github.com/socrata/shipyard/commit/9291b7a342458e5470ea1034030ceed75544b79c

add jq back

---

ruby/2.3.5/Dockerfile

removing GEM stuff which causes seg fault

---

runit-nodejs/10x/Dockerfile

(cherry picked from commit 80f9e6aa1ccd134697c67bbbad4a314f345f677b)

adding 10x node dockerfile for use in polaroid

---

ruby-bionic/2.6.5/Dockerfile
ruby-bionic/README.md

Added various Dockerfile's for Ruby on 18.04.
Ruby 2.5.0, 2.5.3, 2.6.1, and 2.6.3

Ruby on Ubuntu 18.04

---

runit-java8-bionic/Dockerfile

The init system is runit, not sysv init.

Set LD_PRELOAD in runit script

---

ruby-bionic/2.7.2/Dockerfile
ruby-bionic/3.0.0/Dockerfile
ruby-bionic/README.md

Added Dockerfiles to get ruby-bionic building with 2.7.2. and 3.0.0

Build ruby-bionic with ruby versions 2.7.2 and 3.0.0 - EN-44356

---

runit-nodejs-bionic/14x/Dockerfile

Copy/paste/find/replace of 10x.

Add runit-nodejs with nodejs version 14x

---

runit-elixir/Dockerfile

* that's what we have in .tool-version in dsmapi master, anyway

Upgrade to erlang 24 and elixir 1.12

---

base-bionic/Dockerfile
base-bionic/set_metrics_dir
base-bionic/ship
runit-bionic/Dockerfile
runit-bionic/set_metrics_dir
runit-focal/Dockerfile
runit-focal/set_metrics_dir

Balboa-agent is no longer used.

EN-45456 Remove balboa /data/metrics from the Docker image

---

base-bionic/Dockerfile
base-focal/Dockerfile
runit-bionic/Dockerfile
runit-focal/Dockerfile

Add `-m` flag to the `useradd` command so that socrata has a home.
For reference:
https://di-tylertech.slack.com/archives/C2AMTV7RR/p1669995042192249

Create home for socrata user

---

base-focal/Dockerfile
runit-focal/Dockerfile

Per Michael's comment [here](https://github.com/socrata/platform-ui/pull/14907#discussion_r1172692964), this should be fixed in the base images.

EN-58985 - fix jinja templates

---

java-focal/11/Dockerfile
java-focal/17/Dockerfile
java-focal/README.md
runit-java-focal/11/Dockerfile
runit-java-focal/11/collectd-jmx.conf
runit-java-focal/11/set_jmx_hostname
runit-java-focal/17/Dockerfile
runit-java-focal/17/collectd-jmx.conf
runit-java-focal/17/set_jmx_hostname
runit-java-focal/README.md

Looks like we'll be needing at least java 11 for quarkus, might as well add 17 while I'm at it.

Add java 11 and 17 focal images

---

python-focal/3.11/Dockerfile

Additional python tools for venvs and development.

Add some additional python helpers

---

base-focal-ecs/Dockerfile
base-focal-ecs/README.md
base-focal-ecs/ship
base-focal-ecs/ship.d/run
ruby-focal/3.2.x-ecs/Dockerfile
ruby-focal/3.2.x-ecs/hooks/post_push
ruby-focal/3.2.x-ecs/ruby-version.rb

These versions will not set the ARK_HOST or ARK_HOSTNAME variables.

Add ecs compatible versions of base-focal and ruby-focal

---

ruby-focal/3.0.x/Dockerfile
runit-ruby-focal/3.0.x/Dockerfile

Fixing the focal images the same way I fixed the bionic ones in the last PR

Ruby 3.0 fixes for focal images

---

java-focal/23/Dockerfile

Add a `socrata/java-focal:23` version

add java 23 focal image

---

ruby-focal/3.4.x/Dockerfile
ruby-focal/3.4.x/hooks/post_push
ruby-focal/3.4.x/ruby-version.rb
ruby-focal/README.md

```
root@ee3ae6e8c5ba:/# which ruby
/usr/local/bin/ruby
root@ee3ae6e8c5ba:/# ruby --version
ruby 3.4.2 (2025-02-15 revision d2930f8e7a) +PRISM [x86_64-linux]
```

Add ruby-focal-3.4 image
